ka/urls.py
from django.urls import path

from . import views

app_name = 'ka'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('cresults/', views.cresults, name='cresults'),
]

keywords_analyzer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ka.urls')),
    path('admin/', admin.site.urls),
]

ka/views.py
from typing import List

from django.shortcuts import render
from django.views.decorators.http import require_POST

from . import engine


def index(request):
    return render(request, 'ka/index.html')


@require_POST
def results(request):
    url = engine.add_prefix(request.POST["website_url"])
    context = {'errors': 'wrong website'}
    content = engine.simple_get(url)

    if content:
        keywords = engine.find_keywords(content)
        keywords_list = keywords.split(",")

        raw_words = engine.find_words(content)
        words_list = []

        for w in raw_words:
            word = w.lower().split()
            word = engine.clean_wordlist(word)
            if len(word) > 0:
                words_list.append(word)

        words_list = [w for wl in words_list for w in wl]

        words_dict = engine.create_words_dict(words_list)

        keywords_count = engine.find_keywords_in_words(keywords_list, words_dict)

        context = {'keywords_list': keywords_list, 'keywords_count': keywords_count, 'url': url}

    return render(request, 'ka/results.html', context)

ka/templates/ka/base.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'ka/style.css' %}">
</head>



<body>
    <div class="page-header">
        <h1><a href="/">Website keywords analyzer</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

ka/templates/ka/cresults.html
{% extends "ka/base.html" %}

{% block content %}


    {% if errors %}
    {{ errors.upper }}
    {% else %}
    <p>Keyword report of:  <a href="{{ url }}">{{ url }}</a> </p>
    {% if keywords_list %}
        <p>Keywords found:</p>
        {% for k in keywords_list %}
            {{ k }}<br>
        {% endfor %}

    {% else %}
        <p>No keywords found</p>
    {% endif %}
<br>
{#    {{ text }}#}

    {% if keywords_count %}
        <p>Keywords statiscics:</p>
    {% for key, value in keywords_count.items %}
        {{ key }} - {{ value }}<br>
    {% endfor %}
    {% else %}

    {% endif %}
    {% endif %}
    
{% endblock %}

ka/templates/ka/index.html
{% extends "ka/base.html" %}

{% block content %}
    <p>Enter url: </p>

    <form method="post" name="input" action="{% url 'ka:results' %}">
    {% csrf_token %}
        <input type="text" name="website_url" size="100"><br><br>
        <input type="submit" value="Search">
    </form>

{% endblock %}

ka/templates/ka/results.html
{% extends "ka/base.html" %}

{% block content %}


    {% if errors %}
    {{ errors.upper }}
    {% else %}
    <p>Keyword report of:  <a href="{{ url }}">{{ url }}</a> </p>
    {% if keywords_list %}
        <p>Keywords found:</p>
        {% for k in keywords_list %}
            <ul><li>{{ k }}</li></ul>
        {% endfor %}

    {% else %}
        <p>No keywords found</p>
    {% endif %}
<br>
{#    {{ text }}#}

    {% if keywords_count %}
        <p>Keywords statiscics:</p>
    {% for key, value in keywords_count.items %}
        <ul>
        <li> {{ key }} - {{ value }}</li>
        </ul>
    {% endfor %}
    {% else %}

    {% endif %}
    {% endif %}
    
{% endblock %}